languageName: 英文
params:
  description: 为什么使用 Numpy？它有强大的高维数组、有数字计算工具、可操作性强、性能高且开源。
  navbarlogo:
    image: logo.svg
    text: NumPy
    link: /
  hero:
    #Main hero title
    title: NumPy
    #Hero subtitle (optional)
    subtitle: 使用 Python 进行科学计算的基本包
    #Button text
    buttontext: "Latest release: NumPy 2.0. View all releases"
    #Where the main hero button links to
    buttonlink: "/news/#release"
    #Hero image (from static/images/___)
    image: logo.svg
  shell:
    title: 占位符
    intro:
      - 
        title: 尝试使用NumPy
        text: 使用交互式结构在浏览器中尝试使用NumPy
    docslink: 不要忘记查看<a href="https://numpy.org/doc/stable" target="_blank">文档</a>。
  casestudies:
    title: 案例研究
    features:
      - 
        title: 第一张黑洞图像
        text: NumPy 是怎么配合 SciPy 和 Matplotlib 等库来让事件视界望远镜（Eht）生成第一张黑洞图像的
        img: /images/content_images/case_studies/blackhole.png
        alttext: 这是黑洞的第一张图像。它是黑色背景上衬着的一个橙色圆环。
        url: /case-studies/blackhole-image
      - 
        title: 引力波探测
        text: 在1916年，阿尔伯特·爱因斯坦预测了引力波的存在。100年后，激光干涉引力波天文台（LIGO）的科学家利证明了引力波的存在，在实验中就用到了 NumPy。
        img: /images/content_images/case_studies/gravitional.png
        alttext: 两个相互环绕的天体。它们改变了周围的引力。
        url: /case-studies/gw-discov
      - 
        title: Sports Analytics
        text: Cricket Analytics is changing the game by improving player and team performance through statistical modelling and predictive analytics. NumPy enables many of these analyses.
        img: /images/content_images/case_studies/sports.jpg
        alttext: Cricket ball on green field.
        url: /case-studies/cricket-analytics
      - 
        title: Pose Estimation using deep learning
        text: DeepLabCut uses NumPy for accelerating scientific studies that involve observing animal behavior for better understanding of motor control, across species and timescales.
        img: /images/content_images/case_studies/deeplabcut.png
        alttext: Cheetah pose analysis
        url: /case-studies/deeplabcut-dnn
  tabs:
    title: ECOSYSTEM
  section5: false
  navbar:
    - 
      title: Install
      url: /install
    - 
      title: Documentation
      url: https://numpy.org/doc/stable
    - 
      title: Learn
      url: /learn
    - 
      title: Community
      url: /community
    - 
      title: About Us
      url: /about
    - 
      title: News
      url: /news
    - 
      title: Contribute
      url: /contribute
  footer:
    logo: logo.svg
    socialmediatitle: ""
    socialmedia:
      - 
        link: https://github.com/numpy/numpy
        icon: github
      - 
        link: https://www.youtube.com/channel/UCguIL9NZ7ybWK5WQ53qbHng
        icon: youtube
    quicklinks:
      column1:
        title: ""
        links:
          - 
            text: Install
            link: /install
          - 
            text: Documentation
            link: https://numpy.org/doc/stable
          - 
            text: Learn
            link: /learn
          - 
            text: Citing Numpy
            link: /citing-numpy
          - 
            text: Roadmap
            link: https://numpy.org/neps/roadmap.html
      column2:
        links:
          - 
            text: About us
            link: /about
          - 
            text: Community
            link: /community
          - 
            text: User surveys
            link: /user-surveys
          - 
            text: Contribute
            link: /contribute
          - 
            text: Code of conduct
            link: /code-of-conduct
      column3:
        links:
          - 
            text: Get help
            link: /gethelp
          - 
            text: Terms of use
            link: /terms
          - 
            text: Privacy
            link: /privacy
          - 
            text: Press kit
            link: /press-kit
